version: '3.8'

services:

  web:
    build:
      context: .
      dockerfile: docker/Dockerfile.local
    volumes:
    - ./app:/usr/src/app
    ports:
    - 8000:8000
    depends_on:
      db:
        condition: service_healthy
    links:
    - db
    env_file:
      - .env

  # telegram:
  #   build: .
  #   dockerfile: 

  db:
    image: postgres:12.13
    ports:
    - 5433:5432
    volumes:
    - db_data:/var/lib/postgresql/data
    environment:
        POSTGRES_USER: ${DB_USER}
        POSTGRES_PASSWORD: ${DB_PASS}
        POSTGRES_DB: ${DB_BASE}

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_BASE}"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  db_data: