version: '3.8'

services:

  web:
    build:
      context: .
      dockerfile: docker/Dockerfile.local
    volumes:
    - ./app:/usr/src/app
    ports:
    - 8000:8000
    depends_on:
      db:
        condition: service_healthy
    links:
    - db

  db:
    image: postgres:12.13
    ports:
    - 5433:5432
    volumes:
    - db_data:/var/lib/postgresql/data
    environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgres
    - POSTGRES_DB=db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  db_data: